version: "3.7"

services:
  db:
    restart: always
    container_name: matcha
    image: postgres:latest
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    env_file:
      - .env
    volumes:
      - ./db-data/:/var/lib/postgresql/data/


  pg_admin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4_matcha
    ports:
      - "15432:80"
    environment:
      - GUNICORN_THREADS=4
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - db

  redis:
    image: "redis:alpine"
    container_name: redis_matcha
    ports:
      - "${REDIS_PORT}:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    restart: always
