insert into interests (name) values ('Marketing Assistant');
insert into interests (name) values ('Administrative Assistant IV');
insert into interests (name) values ('Executive Secretary');
insert into interests (name) values ('Assistant Professor');
insert into interests (name) values ('Mechanical Systems Engineer');
insert into interests (name) values ('Programmer I');
insert into interests (name) values ('Product Engineer');
insert into interests (name) values ('Engineer III');
insert into interests (name) values ('Payment Adjustment Coordinator');
insert into interests (name) values ('Health Coach III');
insert into interests (name) values ('Office Assistant III');
insert into interests (name) values ('Professor');
insert into interests (name) values ('Technical Writer');
insert into interests (name) values ('Structural Engineer');
insert into interests (name) values ('Administrative Assistant I');
insert into interests (name) values ('Help Desk Operator');
insert into interests (name) values ('Recruiter');
insert into interests (name) values ('Internal Auditor');
insert into interests (name) values ('Marketing Manager');
insert into interests (name) values ('Analyst Programmer');
insert into interests (name) values ('Developer IV');
insert into interests (name) values ('Civil Engineer');
insert into interests (name) values ('Administrative Officer');
insert into interests (name) values ('Account Executive');
insert into interests (name) values ('Pharmacist');
insert into interests (name) values ('Structural Analysis Engineer');
insert into interests (name) values ('Media Manager III');
insert into interests (name) values ('Design Engineer');
insert into interests (name) values ('Editor');
insert into interests (name) values ('Operator');
insert into interests (name) values ('Account Representative IV');
insert into interests (name) values ('Nuclear Power Engineer');
insert into interests (name) values ('Technical Architect');
insert into interests (name) values ('Associate Professor');
insert into interests (name) values ('Clinical Specialist');
insert into interests (name) values ('Legal Assistant');
insert into interests (name) values ('Engineer II');
insert into interests (name) values ('Community Outreach Specialist');
insert into interests (name) values ('Junior Executive');
insert into interests (name) values ('Librarian');
insert into interests (name) values ('Computer Systems Analyst IV');
insert into interests (name) values ('Web Developer II');
insert into interests (name) values ('Web Developer I');
insert into interests (name) values ('VP Product Management');
insert into interests (name) values ('Food Chemist');
insert into interests (name) values ('Nurse Practicioner');
insert into interests (name) values ('Assistant Media Planner');
insert into interests (name) values ('Paralegal');
insert into interests (name) values ('Nurse');
insert into interests (name) values ('Environmental Tech');
insert into interests (name) values ('Social Worker');
insert into interests (name) values ('Sales Representative');
insert into interests (name) values ('VP Quality Control');
insert into interests (name) values ('Programmer Analyst I');
insert into interests (name) values ('Occupational Therapist');
insert into interests (name) values ('Speech Pathologist');
insert into interests (name) values ('Staff Accountant III');
insert into interests (name) values ('Research Nurse');
insert into interests (name) values ('Cost Accountant');
insert into interests (name) values ('Automation Specialist I');
insert into interests (name) values ('Desktop Support Technician');
insert into interests (name) values ('Chief Design Engineer');
insert into interests (name) values ('VP Marketing');
insert into interests (name) values ('Financial Analyst');
insert into interests (name) values ('Project Manager');
insert into interests (name) values ('Developer I');
insert into interests (name) values ('Information Systems Manager');
insert into interests (name) values ('Web Designer I');
insert into interests (name) values ('Quality Control Specialist');
insert into interests (name) values ('Account Coordinator');
